version: '3.8'

services:
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html:cached
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=camagru_db
      - RUN_SETUP=1
      - DB_USER=root
      - DB_PASS=root123

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: camagru_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    depends_on:
      - db

volumes:
  db_data:
